# Sofle FT - builds 5 firmware files:
#   - left OLED + Studio
#   - left nice!view + Studio
#   - right OLED
#   - right nice!view
#   - settings_reset (for clearing BLE)
#
# Choose the UF2 to flash depending on what you have physically soldered on.
---
include:
  # Left with OLED
  - board: nice_nano//zmk
    shield: sofle_left
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_left_oled
  # Left with nice!view
  - board: nice_nano//zmk
    shield: sofle_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_left_niceview
  # Right with OLED
  - board: nice_nano//zmk
    shield: sofle_right
    artifact-name: sofle_right_oled
  # Right with nice!view
  - board: nice_nano//zmk
    shield: sofle_right nice_view_adapter nice_view
    artifact-name: sofle_right_niceview
  # Reset
  - board: nice_nano//zmk
    shield: settings_reset
